services:
  # server:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     NODE_ENV: dev
  #   ports:
  #     - 3000:3000
  # The commented out section below is an example of how to define a PostgreSQL
  # database that your application can use. `depends_on` tells Docker Compose to
  # start the database before your application. The `db-data` volume persists the
  # database data between container restarts. The `db-password` secret is used
  # to set the database password. You must create `db/password.txt` and add
  # a password of your choosing to it before running `docker-compose up`.
  # depends_on:
  #   db:
  #     condition: service_healthy

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=spotify
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
